### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "john_doe",
  "password": "123456"
}

### List tasks
GET http://localhost:8080/tasks
Authorization: Basic am9obl9kb2U6MTIzNDU2
Content-Type: application/json

### Create task
POST http://localhost:8080/tasks
Authorization: Basic am9obl9kb2U6MTIzNDU2
Content-Type: application/json

{
  "title": "Implementar To Do API",
  "description": "Implementar to do api com Java e Spring Boot.",
  "priority": "high",
  "startedAt": "2024-09-12T09:00:00",
  "finishedAt": "2024-09-13T17:00:00"
}

### Update task
PUT http://localhost:8080/tasks/5fe7ccf9-0b86-41d3-8964-2e56120ba340
Authorization: Basic am9obl9kb2U6MTIzNDU2
Content-Type: application/json

{
  "title": "Atualizado tarefa",
  "description": "Implementar to do api com Java e Spring Boot.",
  "priority": "high",
  "startedAt": "2024-09-12T09:00:00",
  "finishedAt": "2024-09-13T17:00:00"
}

### Partial update task
PATCH http://localhost:8080/tasks/5fe7ccf9-0b86-41d3-8964-2e56120ba340
Authorization: Basic am9obl9kb2U6MTIzNDU2
Content-Type: application/json

{
  "priority": "medium"
}
