### POST Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "john_doe",
  "password": "123456"
}

### POST Create task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Implementar To Do API",
  "description": "Implementar to do api com Java e Spring Boot.",
  "priority": "high",
  "startedAt": "2024-09-11T09:00:00",
  "finishedAt": "2024-09-12T17:00:00",
  "userId": "887f06c3-7975-4332-adc8-471476f36940"
}
